### PR TITLE
Remove broken go 1.23.1

### LINKED ISSUE #60: Builders are getting stuck on `go install`
```
 + go install golang.org/x/vuln/cmd/govulncheck@latest
go: downloading golang.org/x/vuln v1.1.3
go: downloading golang.org/x/telemetry v0.0.0-20240522233618-39ace7a40ae7
go: downloading golang.org/x/mod v0.19.0
go: downloading golang.org/x/tools v0.23.0
go: downloading golang.org/x/sync v0.7.0
{"component":"entrypoint","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:169","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 4h0m0s timeout","severity":"error","time":"2024-09-12T12:28:29Z"}
{"component":"entrypoint","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:267","func":"sigs.k8s.io/prow/pkg/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 15m0s grace period","severity":"error","time":"2024-09-12T12:43:29Z"} 
```
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/logs/post-scylla-operator-images-master-images/1834147040985092096#1:build-log.txt%3A1676

This has happened quite often and without any obvious cause.

### PR DESCRIPTION
**Pull request by tnozicka**
Almost all builds of go 1.23 are getting stuck installing govulncheck and we haven't had a successful promoion since 1.23 landed as all jobs timeout (#60)
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/logs/post-scylla-operator-images-master-images/1834147040985092096
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/logs/post-scylla-operator-images-master-images/1834211463124750336
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/logs/post-scylla-operator-images-master-images/1834566857709850624
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/logs/post-scylla-operator-images-master-images/1834571381312851968
this seems to be similar to github.com/golang/go/issues/68976

This PR removes the broken golang 1.23.1 until there is a new version with fix.

Resolves #60

### CODE REVIEW

**Review by rzetelskik — APPROVED** [review]
lgtm
/assign zimnx

**Comment by tnozicka** [comment]
/hold
seen with go 1.21.6 as well

**Comment by tnozicka** [comment]
It got stuck on other versions as well and turned out to be an issue with `qemu-user-static` binary that has been addressed by compiling a newer version from source and disabling LTO.

**Pull request closed without merging**
