### PR TITLE
Add mdadm to node-setup image

### PR DESCRIPTION
**Pull request by zimnx**
It's going to be used in upcoming disk setup e2e.

### CODE REVIEW

**Review by tnozicka — COMMENTED** [review]
is there a technical reason you need this in the base image? it doesn't fall into a category "needed in every single image we build"

**Review by tnozicka — DISMISSED** [review]
/approve
/lgtm

**Comment by zimnx** [comment]
clean push to retrigger the CI

**Comment by zimnx** [comment]
nothing happened, @tnozicka PTAL whether CI settings are ok, i don't have enough permissions in this repo.

**Review by tnozicka — DISMISSED** [review]

**Pull request closed without merging**
