### PR TITLE
Add netcat to node-setup helper image

### PR DESCRIPTION
**Pull request by zimnx**
Image is used only in Operator E2E tests.

Required by https://github.com/scylladb/scylla-operator/pull/2175

### CODE REVIEW

**Review by tnozicka — COMMENTED** [review]
/approve

/hold
for all reviews on https://github.com/scylladb/scylla-operator/pull/2175

**Comment by tnozicka** [comment]
/hold cancel
https://github.com/scylladb/scylla-operator/pull/2175#issuecomment-2447400081

**Comment by zimnx** [comment]
arm64 build got stuck, retry
/retest

**Pull request merged**
