### PR TITLE
Add Go 1.21 image

### PR DESCRIPTION
**Pull request by zimnx**
This adds an image with Go 1.21.3

### CODE REVIEW

**Comment by rzetelskik** [comment]
1.21.3 was released yesterday with a security fix, let's update?

**Comment by zimnx** [comment]
> 1.21.3 was released yesterday with a security fix, let's update?

done, thanks

**Comment by rzetelskik** [comment]
/approve
and lgtm

/assign @tnozicka

**Review by tnozicka — APPROVED** [review]
/approve
/lgtm

/retest

**Pull request merged**
