### PR TITLE
Update golang versions

### PR DESCRIPTION
**Pull request by tnozicka**
Updates all golang versions to the latest z-stream.

### CODE REVIEW

**Comment by tnozicka** [comment]
/hold
(I want to test govulncheck periodic fails before this lands)

**Review by rzetelskik — APPROVED** [review]
/lgtm
thanks!

**Comment by tnozicka** [comment]
> wait, why isn't this bumping the versions to 1.21.6 and 1.20.13?

well, I've made these change yesterday and the made a release later that day - I'll bump it

**Pull request merged**
