### PR TITLE
Update golang to 1.22.9 and 1.23.3

### PR DESCRIPTION
**Pull request by tnozicka**
This PR updates golang patch versions to the latest 1.22.9 and 1.23.3.

Fingers crossed for the cross-builds, although the chances aren't high.

### CODE REVIEW

**Review by zimnx — APPROVED** [review]
/lgtm

**Comment by tnozicka** [comment]
the timeout is still there https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator-images/77/pull-scylla-operator-images-images/1854455158692384768#1:build-log.txt%3A1676
(the update is valid anyway, just did fix the wishful thinking we had)

**Pull request merged**
