### PR TITLE
Update golang versions

### PR DESCRIPTION
**Pull request by tnozicka**
This PR updates go1.22 to the latest z-stream (.7), removed no longer supported go1.21 and add go 1.23.1.

It also bumps yq to v4.44.3.

### CODE REVIEW

**Review by zimnx — APPROVED** [review]
/lgtm

**Review by zimnx — APPROVED** [review]
/lgtm

**Comment by tnozicka** [comment]
repeating timeouts
https://github.com/scylladb/scylla-operator-release/pull/320

**Comment by tnozicka** [comment]
https://github.com/scylladb/scylla-operator-release/pull/320 landed
/retest

**Pull request merged**
